networks:
    dev:

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:8000
    networks:
      - dev
    volumes:
      - /root/chat/nginx/nginx.conf:/etc/nginx/nginx.conf

  api:
    container_name: api
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
    - 8000:8000
    networks:
      - dev  
    depends_on:
      - db
    
  db:
    image: postgres
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    networks:
      - dev