services:
  nginx:
    image: nginx
    container_name: server
    ports:
      - 8001:80
  
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
  
  db:
    image: postgres
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db