networks:
    - dev

services:
  nginx:
    image: nginx
    container_name: server
    ports:
      - 8000:80
    networks:
      - dev
  
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
    - 8000:8000
    networks:
      - dev  
  
  db:
    image: postgres
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    networks:
      - dev