# Generated by Django 5.1.4 on 2024-12-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=40, verbose_name='Имя пользователя')),
                ('last_name', models.CharField(max_length=40, verbose_name='Фамилия пользователя')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Почта пользователя')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
