# Generated by Django 5.1.4 on 2025-01-02 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название чата')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Private chat'), (1, 'Group chat')], default=1, verbose_name='Тип чата')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'INACTIVE'), (1, 'ACTIVE')], default=1, verbose_name='Статус активности')),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Контент сообщения')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='Статус')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_room', to='chat.room', verbose_name='Название чата')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
